### ISSUE TITLE
Use a single field instead of two

### ISSUE THREAD

**Issue by SergeyKanzhelev** [w3c/trace-context-binary#7]
From @bogdandrutu

https://github.com/w3c/trace-context-binary/pull/2#issuecomment-483812587

Propose to have only one binary value for the encoding result, by unifying traceparent and tracestate.

``` js
{0,  // version
  0 /* id */ , 75, 249, 47, 53, 119, 179, 77, 166, 163, 206, 146, 157, 0, 14, 71, 54,  // trace-id
  1 /* id */, 52, 240, 103, 170, 11, 169, 2, 183,  // span-id
  2 /* id */, 1,  // trace-options
  3 /* id */, ...  // tracestate (probably prefixed with the len to allow easy parsing)
}
```

This will simplify integrations with grpc or other binary protocols. Also from the tracing library perspective this will simplify the propagation framework (accepts byte[] and returns byte[]).

**Comment by SergeyKanzhelev** [comment]
> `(probably prefixed with the len to allow easy parsing)`

I don't think `len` will be needed. Length calculation will require two passes when serializing into binary and have very little utility as presumably you will need to parse `tracestate` anyway.

Making `traceparent` and `tracestate` a single field will require to come up with the new name to store this field in protocols like AMQP. Like `tracecontext`. Which may confuse implementors.

What's the biggest motivation for you to have it as a single field?

**Comment by yurishkuro** [comment]
+1 to a single binary struct / blob. I would also consider making tracestate field fully structured, i.e. as an array of key=value pairs.

**Comment by SergeyKanzhelev** [comment]
@yurishkuro what's the main reason for you to have a single blob?

**Comment by yurishkuro** [comment]
In the OpenTracing API if you want to convert trace context to binary, you only get a single blob. For that matter, including the correlation context into the same binary would be good.

Otherwise the BINARY format needs to be re-designed similar to TEXT_MAP, as a collection of field->blob entries.

**Comment by SergeyKanzhelev** [comment]
@yurishkuro I understand there are libraries that has specific implementations. Presumably those implementations design decisions were made based on some assumptions and benefits of a single blob over multiple. Perhaps some limitatiosn of specific binary protocols. Can you comment on the benefits of a single blob from this angle?

I can see how single blob can be more compact for protocols carrying metadata about every field. 

As of cons - there will be a new name for the "coimbined" field that may confuse as it will create inconsistency with the http protocol. For instance, if binary will be used with AMQP - it will not be inconsistent to only have a single field in metadata there while in HTTP two headers are used.

**Comment by yurishkuro** [comment]
I don't have an example of a protocol that would require a single blob; interested to hear examples if others ran into that. I thought Cassandra did that, but just looked through it and it also supports key/value metadata, so would work fine with multiple fields.

There are probably minor efficiency gains from using a single byte buffer vs. several, but it can be addressed by pooling.

So changing my vote to "don't care" - multiple fields are fine too.

**Comment by SergeyKanzhelev** [comment]
@yurishkuro noted!

@bogdandrutu were your original suggestion based on some experience with specific protocols, based on perf considerations, or something else?

**Comment by tedsuo** [comment]
Often, binary interfaces are streaming, so a single blob may be more portable. Otherwise we are assuming that binary is only for carriers with properly structured metadata.

Of course, it is feasible for a system to glue multiple binary blobs together in some way. But the receiving system would also need to know how to unglue them. So I suspect a single blob would be better.

I don't have a specific example, so consider this an unfounded concern.

**Comment by yurishkuro** [comment]
> I don't have a specific example

I think this is the key here - can anyone provide an example of a protocol where an opaque binary blob  would actually work?

**Comment by bogdandrutu** [comment]
If you are allowed to have a single blob most likely you are allowed to have two as well. We will have at least 2 blobs anyway for trace and tags.

In gRPC (at least Java) it is easier if you have a single blob based on their way to define Metadata, but having 2 is not impossible. May be a bit ugly, and arguably a bit slower (we need to create a wrapper object on top of the two metadata that we will have, this applies to any binary protocol in general).

**Comment by yurishkuro** [comment]
I changed my mind, +1 for two fields

**Comment by SergeyKanzhelev** [comment]
It looks like this issue was discussed and we didn't find a specific examples where two fields will not work. Please re-open this issue if you have a specific example to discuss
